version: '2'
services:
  metrictank:
    hostname: metrictank-1
    build: metrictank/
    ports:
     - "6060:6060"
     - "2003:2003"
    depends_on:
     - statsdaemon
     - cassandra
     - elasticsearch
  cassandra:
    image: cassandra:3.0.8
  statsdaemon:
    hostname: statsdaemon-1
    build: statsdaemon/
    ports:
     - "8125:8125/udp"
  graphite-api:
    hostname: graphite-api-1
    build: graphite-api/
    ports:
     - "8080:8080"
    depends_on:
     - metrictank
     - statsdaemon
     - elasticsearch
  elasticsearch:
    image: elasticsearch
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - graphite-api
