finders:
- graphite_metrictank.RaintankFinder
functions:
- graphite_api.functions.SeriesFunctions
- graphite_api.functions.PieFunctions
statsd:
  host: 'statsdaemon'
  port: 8125
logging:
  version: 1
  handlers:
    raw:
      level: INFO
      class: logging.StreamHandler
      formatter: raw
  loggers:
    root:
      handlers:
        - raw
      level: INFO
      propagate: false
    graphite_api:
      handlers:
        - raw
      level: INFO
  formatters:
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  root:
    level: ERROR
allowed_origins:
  - localhost:3000
raintank:
  tank:
    url: http://metrictank:6060/
search_index: /var/lib/graphite/index
time_zone: UTC

